services:
  backend:
    build: .
    ports:
      - 8080:8080
      - 9229:9229 # for debugging
    environment:
      PORT: ${PORT}
  postgres:
    image: postgres:15-alpine
    ports: 
      - 5432:5432