services:
  postgres:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: scoob_prod
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    environment:
      - NODE_ENV=production
    command: npm run prod
    depends_on:
      - postgres
  
